"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import spirvsmith_server_sdk
from spirvsmith_server_sdk.model.buffer_submission import BufferSubmission


class TestBufferSubmission(unittest.TestCase):
    """BufferSubmission unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBufferSubmission(self):
        """Test BufferSubmission"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BufferSubmission()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
