"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import spirvsmith_server_sdk
from spirvsmith_server_sdk.model.buffer_submission import BufferSubmission
from spirvsmith_server_sdk.model.execution_platform import ExecutionPlatform
globals()['BufferSubmission'] = BufferSubmission
globals()['ExecutionPlatform'] = ExecutionPlatform
from spirvsmith_server_sdk.model.body_submit_buffers_buffers_shader_id_post import BodySubmitBuffersBuffersShaderIdPost


class TestBodySubmitBuffersBuffersShaderIdPost(unittest.TestCase):
    """BodySubmitBuffersBuffersShaderIdPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBodySubmitBuffersBuffersShaderIdPost(self):
        """Test BodySubmitBuffersBuffersShaderIdPost"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BodySubmitBuffersBuffersShaderIdPost()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
