"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import spirvsmith_server_sdk
from spirvsmith_server_sdk.model.hardware_type import HardwareType


class TestHardwareType(unittest.TestCase):
    """HardwareType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHardwareType(self):
        """Test HardwareType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HardwareType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
