"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import spirvsmith_server_sdk
from spirvsmith_server_sdk.model.hardware_type import HardwareType
from spirvsmith_server_sdk.model.hardware_vendor import HardwareVendor
globals()['HardwareType'] = HardwareType
globals()['HardwareVendor'] = HardwareVendor
from spirvsmith_server_sdk.model.hardware_information import HardwareInformation


class TestHardwareInformation(unittest.TestCase):
    """HardwareInformation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHardwareInformation(self):
        """Test HardwareInformation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HardwareInformation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
