"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import spirvsmith_server_sdk
from spirvsmith_server_sdk.model.generator_info import GeneratorInfo
globals()['GeneratorInfo'] = GeneratorInfo
from spirvsmith_server_sdk.model.shader_submission import ShaderSubmission


class TestShaderSubmission(unittest.TestCase):
    """ShaderSubmission unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testShaderSubmission(self):
        """Test ShaderSubmission"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ShaderSubmission()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
