"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import spirvsmith_server_sdk
from spirvsmith_server_sdk.model.mutations_config import MutationsConfig
globals()['MutationsConfig'] = MutationsConfig
from spirvsmith_server_sdk.model.fuzzing_strategy import FuzzingStrategy


class TestFuzzingStrategy(unittest.TestCase):
    """FuzzingStrategy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFuzzingStrategy(self):
        """Test FuzzingStrategy"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FuzzingStrategy()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
