"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import spirvsmith_server_sdk
from spirvsmith_server_sdk.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_flush_queues_queues_delete(self):
        """Test case for flush_queues_queues_delete

        Flush Queues  # noqa: E501
        """
        pass

    def test_get_next_shader_next_shader_post(self):
        """Test case for get_next_shader_next_shader_post

        Get Next Shader  # noqa: E501
        """
        pass

    def test_get_queues_queues_get(self):
        """Test case for get_queues_queues_get

        Get Queues  # noqa: E501
        """
        pass

    def test_get_queues_queues_queue_id_get(self):
        """Test case for get_queues_queues_queue_id_get

        Get Queues  # noqa: E501
        """
        pass

    def test_get_shader_shaders_shader_id_get(self):
        """Test case for get_shader_shaders_shader_id_get

        Get Shader  # noqa: E501
        """
        pass

    def test_register_executor_executors_post(self):
        """Test case for register_executor_executors_post

        Register Executor  # noqa: E501
        """
        pass

    def test_register_generator_generators_post(self):
        """Test case for register_generator_generators_post

        Register Generator  # noqa: E501
        """
        pass

    def test_root_get(self):
        """Test case for root_get

        Root  # noqa: E501
        """
        pass

    def test_submit_buffers_buffers_shader_id_post(self):
        """Test case for submit_buffers_buffers_shader_id_post

        Submit Buffers  # noqa: E501
        """
        pass

    def test_submit_shader_shaders_post(self):
        """Test case for submit_shader_shaders_post

        Submit Shader  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
