"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import spirvsmith_server_sdk
from spirvsmith_server_sdk.model.location_inner import LocationInner


class TestLocationInner(unittest.TestCase):
    """LocationInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLocationInner(self):
        """Test LocationInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LocationInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
