"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import spirvsmith_server_sdk
from spirvsmith_server_sdk.model.hardware_information import HardwareInformation
from spirvsmith_server_sdk.model.operating_system import OperatingSystem
from spirvsmith_server_sdk.model.vulkan_backend import VulkanBackend
globals()['HardwareInformation'] = HardwareInformation
globals()['OperatingSystem'] = OperatingSystem
globals()['VulkanBackend'] = VulkanBackend
from spirvsmith_server_sdk.model.execution_platform import ExecutionPlatform


class TestExecutionPlatform(unittest.TestCase):
    """ExecutionPlatform unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExecutionPlatform(self):
        """Test ExecutionPlatform"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ExecutionPlatform()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
