# coding: utf-8

"""
    SPIRVSmith-Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from spirvsmith_server_sdk.api_client import ApiClient
from spirvsmith_server_sdk.api.default_api_endpoints.flush_queues_queues_delete import FlushQueuesQueuesDelete
from spirvsmith_server_sdk.api.default_api_endpoints.get_next_shader_shaders_next_post import GetNextShaderShadersNextPost
from spirvsmith_server_sdk.api.default_api_endpoints.get_queue_queues_queue_id_get import GetQueueQueuesQueueIdGet
from spirvsmith_server_sdk.api.default_api_endpoints.get_queues_queues_get import GetQueuesQueuesGet
from spirvsmith_server_sdk.api.default_api_endpoints.get_shader_shaders_shader_id_get import GetShaderShadersShaderIdGet
from spirvsmith_server_sdk.api.default_api_endpoints.register_executor_queues_put import RegisterExecutorQueuesPut
from spirvsmith_server_sdk.api.default_api_endpoints.register_generator_generators_post import RegisterGeneratorGeneratorsPost
from spirvsmith_server_sdk.api.default_api_endpoints.submit_buffers_buffers_shader_id_post import SubmitBuffersBuffersShaderIdPost
from spirvsmith_server_sdk.api.default_api_endpoints.submit_shader_shaders_post import SubmitShaderShadersPost


class DefaultApi(
    FlushQueuesQueuesDelete,
    GetNextShaderShadersNextPost,
    GetQueueQueuesQueueIdGet,
    GetQueuesQueuesGet,
    GetShaderShadersShaderIdGet,
    RegisterExecutorQueuesPut,
    RegisterGeneratorGeneratorsPost,
    SubmitBuffersBuffersShaderIdPost,
    SubmitShaderShadersPost,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
