# coding: utf-8

"""
    SPIRVSmith-Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from spirvsmith_server_sdk.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class ShaderSubmission(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    _required_property_names = set((
        'shader_id',
        'shader_assembly',
        'generator_info',
        'prioritize',
        'n_buffers',
    ))
    shader_id = StrSchema
    shader_assembly = StrSchema

    @classmethod
    @property
    def generator_info(cls) -> typing.Type['GeneratorInfo']:
        return GeneratorInfo
    prioritize = BoolSchema
    n_buffers = IntSchema


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        shader_id: shader_id,
        shader_assembly: shader_assembly,
        generator_info: generator_info,
        prioritize: prioritize,
        n_buffers: n_buffers,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'ShaderSubmission':
        return super().__new__(
            cls,
            *args,
            shader_id=shader_id,
            shader_assembly=shader_assembly,
            generator_info=generator_info,
            prioritize=prioritize,
            n_buffers=n_buffers,
            _configuration=_configuration,
            **kwargs,
        )

from spirvsmith_server_sdk.model.generator_info import GeneratorInfo
