# coding: utf-8

"""
    SPIRVSmith-Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import spirvsmith_server_sdk
from spirvsmith_server_sdk.model.operating_system import OperatingSystem


class TestOperatingSystem(unittest.TestCase):
    """OperatingSystem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def test_OperatingSystem(self):
        """Test OperatingSystem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OperatingSystem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
